[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#0d6efd"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#fafafa"
font = "sans serif"
